### ISSUE TITLE
Extract XML attributes of all features

### ISSUE THREAD

**Issue by planemad** [ramSeraph/indian_cadastrals#1]
Ref: https://github.com/publicmap/3d-goa/issues/38

Certain villages in Goa still had the GeoRSS XML instead of the parsed attributes. Is there a better place to file this ticket @ramSeraph ?

Location: https://indianopenmaps.fly.dev/not-so-open/cadastrals/goa/bhunaksha/view#17.11/15.585298/73.753924

<img width="394" alt="Screenshot 2024-12-10 at 7 38 32 PM" src="https://github.com/user-attachments/assets/15126d69-9cc5-49f6-bc3d-4cb0bc98a9e3">

And thank you ❤️ . This greatly eases of access to information to the public that was unnecessarily expensive.

**Comment by planemad** [comment]
Issue seems to be limited to only a single village - Anjuna. Everything else looks fine.

**Comment by ramSeraph** [comment]
Should be fixed now.. purge browser cache if needed to verify.

**Comment by ramSeraph** [comment]
@planemad this might be the first deployment of one of the layers.. if anything breaks drop an issue at https://github.com/ramSeraph/indianopenmaps .

**Comment by planemad** [comment]
🙏 

![licecap2](https://github.com/user-attachments/assets/3b530204-7d18-4e22-984d-850ab5778007)
